apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../bases/gitexpex
 - ../../bases/gitexampler
 - ../../bases/giter
 - ../../bases/gitexample
 - ../../bases/gitexamplesddsaffs
