apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  ## Broker Lead
  - ../../bases/{{ baseName }}
  - onedealer-participation/onedealer-webservice-credentials-ss.yaml

  ## oneDealer Admin
  - onedealer-admin/onedealer-admin-basic-auth-ss.yaml

  ## qa auth ingress for broker lead
  - broker-lead/broker-lead-ing-qa-user-auth.yaml
  - krankikom-participation/krankikom-api-credentials-ss.yaml

vars:
  {% if not environment.useCase.brokerLeadDomain == "" %}
  - name: BROKER_LEAD_SUBDOMAIN
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: retail-config
    fieldref:
      fieldpath: data.BROKER_LEAD_TLD
  {% else %}
  - name: BROKER_LEAD_SUBDOMAIN
    objref:
      group: networking.k8s.io
      apiVersion: v1
      kind: Ingress
      name: broker-lead
  {% endif %}
  {% if not environment.useCase.oneDealerAdminDomain == "" %}
  - name: ONE_DEALER_ADMIN_SUBDOMAIN
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: retail-config
    fieldref:
      fieldpath: data.ONE_DEALER_ADMIN_TLD
  {% else %}
  - name: ONE_DEALER_ADMIN_SUBDOMAIN
    objref:
      group: networking.k8s.io
      apiVersion: v1
      kind: Ingress
      name: onedealer-admin
  {% endif %}

  - name: QA_USER_AUTH_URL_SUFFIX
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: retail-config
    fieldref:
      fieldpath: data.QA_USER_AUTH_URL_SUFFIX

configMapGenerator:
  # Apply settings related to the distributor test system.
  # The assumption is that distributors try out features from the aggregators before they bring it
  # in production.
  - name: retail-config
    behavior: merge
    literals:
      - RETAIL_TLD=".{{ environment.clusterTld }}"
      {% if environment.useCase.brokerLeadDomain %}
      - BROKER_LEAD_DOMAIN="{{ environment.useCase.brokerLeadDomain }}"
      {% else %}
      - BROKER_LEAD_TLD=".{{ environment.clusterTld }}"
      {% endif %}
      {% if environment.useCase.oneDealerAdminDomain %}
      - ONE_DEALER_ADMIN_DOMAIN="{{ environment.useCase.oneDealerAdminDomain }}"
      {% else %}
      - ONE_DEALER_ADMIN_TLD=".{{ environment.clusterTld }}"
      {% endif %}
      - QA_USER_AUTH_URL_SUFFIX="-dex"

  - name: onedealer-participation-service
    behavior: merge
    literals:
      - ONEDEALER_CLIENT_BASE_URL="{{ environment.useCase.oneDealerApi }}"
      - ONEDEALER_CLIENT_TIMEOUT=120s

  - name: krankikom-participation-service
    behavior: merge
    literals:
      - KRANKIKOM_CLIENT_BASE_URL="{{ environment.useCase.krankikomApi }}"

  - name: onedealer-status-upload
    behavior: merge
    literals:
      - ENABLE_PUBLISH_ON_UPLOAD=true


  - name: onedealer-status-upload-business-transaction-event-topic
    behavior: merge
    literals:
      - KAFKA_TOPICS_BUSINESS_TRANSACTION_NAME="business-transaction-event"

  {% if distributor.frontend.trackingEnabled %}
  - name: hukautowelt-retail-tracking-id
    behavior: merge
    literals:
      - TRACKING_ID="{{ environment.gaTrackingId }}"
  {% endif %}

  - name: use-case-initializer
    behavior: merge
    literals:
      - DISTRIBUTOR_ID={{ distributor.id }}
patches:
  - target:
      kind: Ingress
      name: broker-lead
    patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: broker-lead
        annotations:
          nginx.ingress.kubernetes.io/auth-url: {{ ( environment.brokerAuthBaseUrl + '/oauth2/auth') | tojson }}
          nginx.ingress.kubernetes.io/auth-signin: {{ ( environment.brokerAuthBaseUrl + '/oauth2/start?rd=https://$host$escaped_request_uri') | tojson }}
  - target:
      kind: Ingress
      name: broker-lead-qa-auth
    patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: broker-lead-qa-auth
        annotations:
          nginx.ingress.kubernetes.io/auth-url: {{ ( environment.qaUserAuthBaseUrl + '/oauth2/auth') | tojson }}
          nginx.ingress.kubernetes.io/auth-signin: {{ ( environment.qaUserAuthBaseUrl + '/oauth2/start?rd=https://$host$escaped_request_uri') | tojson }}
  {% if not environment.productionEnvironment %}
  - target:
      group: persistence.sda-se.com
      version: v1beta1
      kind: MongoDb
    patch: |
      - op: replace
        path: /spec/database/pruneAfterDelete
        value: true
  {% endif %}
